StudioLibrary: Prefab Rig support
SunriseProductions/studiolibrary pull request #2
Opened 2023-12-04 09:15 UTC by dirk-coetzee

Added prefab rig support to Studio Library.

2023-12-04 11:40 UTC, DexterSchenk requested changes

2023-12-04 11:40 UTC, DexterSchenk commented on src/mutils/gui/modelpanelwidget.py
> +        #//maya.cmds.modelEditor(modelPanel, edit=True, allObjects=False)
is this meant to be commented out?

2023-12-04 11:40 UTC, DexterSchenk commented on src/studiolibrary/config/config.json
>  }
missing new line at EOF

2023-12-04 11:40 UTC, DexterSchenk commented on src/mutils/__init__.py
> +from .prefab import Prefab, savePrefab, loadPrefab
missing new line at EOF

2023-12-04 12:28 UTC, dane-coetzee commented on src/mutils/gui/modelpanelwidget.py
> +        #//maya.cmds.modelEditor(modelPanel, edit=True, allObjects=False)
Yeah this is intentional, I could not get the playblast to show the prefab when running a headless publish with that turned on.

2023-12-04 13:06 UTC, dane-coetzee commented on src/mutils/__init__.py
> +from .prefab import Prefab, savePrefab, loadPrefab
This line is actually not needed, since that module doesn't exist anymore. I'll remove it

2023-12-04 13:07 UTC, dane-coetzee commented on src/studiolibrary/config/config.json
>  }
Fixed, I noticed the default.json is allso missing a new line. Will add one there too

2023-12-04 13:11 UTC, dane-coetzee commented on src/mutils/__init__.py
@DexterSchenk This commit was me adding the new lines as requested, but it seems to be stripping them out again. Am I doing something wrong?

2023-12-05 07:33 UTC, DexterSchenk approved these changes

2023-12-05 07:33 UTC, merged